last_server:lastA_server.cpp
	g++ -Wall -std=c++11 -O3 lastA_server.cpp -o last_server
A_search:progA_search.cpp
	g++ -Wall -O3 progA_search.cpp -o A_search
tuning:tuning_data.cpp
	g++ -Wall -std=c++17 -O3 tuning_data.cpp -o tuning
