last_server:lastA_server.cpp
	g++ -pthread -Wall -std=c++11 -O3 lastA_server.cpp TCPServerMT.cpp libserver.cpp -o last_server
	g++ -Wall -std=c++11 -O3 libclient.cpp TCPClientC1.cpp -o client
A_search:progA_search.cpp
	g++ -Wall -O3 progA_search.cpp -o A_search
tuning:tuning_data.cpp
	g++ -Wall -std=c++17 -O3 tuning_data.cpp -o tuning
